version: "3.8"
services:
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
    - "6379:6379"
    environment:
    - REDIS_REPLICATION_MODE=slave
    - REDIS_MASTER_HOST=redis-master
    - REDIS_MASTER_PORT_NUMBER=6379
    - REDIS_MASTER_PASSWORD=RohF3wooj9eefe
    - REDIS_PASSWORD=Mohsh8ahc2shib
    networks:
    - backend-network
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    environment:
    - MONGO_INITDB_DATABASE=bookaloo
    volumes:
    - ./mongodb-data:/data/db
    - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
    - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
    - backend-network
  backend:
    build: ./backend
    container_name: backend
    ports:
    - 5000:5000
    volumes:
    - ./backend:/app
    restart: unless-stopped
    depends_on:
    - mongodb
    - redis-server
    networks:
    - backend-network
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
    - 3000:3000
    volumes:
    - ./frontend:/app
    restart: unless-stopped
    depends_on:
    - backend
    networks:
    - backend-network

volumes:
  mongodb-data:
  backend:
  frontend:

networks:
  backend-network: