export const responses = {
    LOGIN_FAILED: "Login failed",
    ADDING_AUTHOR_FAILED: "Adding author failed",
    EDITING_AUTHOR_FAILED: "Editing author failed",
    REMOVING_AUTHOR_FAILED: "Removing author failed",
    LOGIN_SUCCEEDED: "Login succeeded",
    ADDING_AUTHOR_SUCCEEDED: "Adding author succeeded",
    EDITING_AUTHOR_SUCCEEDED: "Editing author succeeded",
    REMOVING_AUTHOR_SUCCEEDED: "Removing author succeeded",
    ADDING_BOOK_FAILED: "Adding book failed",
    EDITING_BOOK_FAILED: "Editing book failed",
    REMOVING_BOOK_FAILED: "Removing book failed",
    ADDING_BOOK_SUCCEEDED: "Adding book succeeded",
    EDITING_BOOK_SUCCEEDED: "Editing book succeeded",
    REMOVING_BOOK_SUCCEDED: "Removing book succeeded",
    FETCHING_AUTHOR_FAILED: "Fetching author failed",
    FETCHING_AUTHORS_FAILED: "Fetching authors failed",
    FETCHING_BOOK_FAILED: "Fetching book failed",
    FETCHING_BOOKS_FAILED: "Fetching books failed",
    FETCHING_AUTHOR_SUCCEEDED: "Fetching author succeeded",
    FETCHING_AUTHORS_SUCCEEDED: "Fetching authors succeeded",
    FETCHING_BOOK_SUCCEEDED: "Fetching book succeeded",
    FETCHING_BOOKS_SUCCEEDED: "Fetching books succeeded",
    SOMETHING_WENT_WRONG: "Something went wrong",
    YOU_SHALL_NOT_PASS: "You shall not pass!",
    WRONG_PASSWORD: "Wrong password",
    WRONG_EMAIL: "Wrong email",
    YOU_CAN_NOT_ACCESS_THIS_RESOURCE: "You can not access this resource",
    TOKEN_NOT_PRESENT: "Token not present",
    TOKEN_HAS_EXPIRED: "Token has expired"
}
